export const fontFamilies = [
    'Inter',
    'Open Sans',
    'Noto Sans',
    'Roboto',
    'Poppins',
    'Montserrat',
    'Lato',
    'Manrope',
    'Ubuntu',
    'Figtree',
    'Fira Sans',
    'Fira Code',
    'Fira Mono',
    'Source Code Pro',
    'IBM Plex Mono',
    'JetBrains Mono',
];

export const fontWeight = [
    {value: 100, label: 'Thin'},
    {value: 200, label: 'Extra Light'},
    {value: 300, label: 'Light'},
    {value: 400, label: 'Regular'},
    {value: 500, label: 'Medium'},
    {value: 600, label: 'Semi Bold'},
    {value: 700, label: 'Bold'},
    {value: 800, label: 'Extra Bold'},
    {value: 900, label: 'Black'},
];